name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: branch

      - name: Add token for Font Awesome registry access
        env:
          FA_TOKEN: ${{ secrets.FA_TOKEN }}
        run: npm run add-fa-config

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build documentation and demo site
        run: npm run build-demo-site

      - name: Run semantic release and publish new version to npm
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

      - name: Deploy documentation to GitHub Pages
        if: github.ref == 'ref/head/master'
        uses: JamesIves/github-pages-deploy-action@3.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/web # The folder the action should deploy.
          #TARGET_FOLDER: ${{ steps.branch.outputs.branch }} # The folder the action should deploy to.
